name: Deploy

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: |
          echo "Submodule update"
          git submodule update --init 
          echo "Installing gems"
          bundle install
      - name: Generate guides files
        run: rake assets:precompile
      - name: Setup
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          echo PR_NUMBER=${{ github.event.number }} >> $GITHUB_ENV
      - name: Commit site changes
        run: |
          git checkout -b site
          git add site/
          git commit -m "Build from commit ${GITHUB_SHA}"
          git push origin site --force
      - name: Comment on merged pull request
        run: |
          curl --silent --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
          --header 'Accept: application/vnd.github.squirrel-girl-preview' \
          --header 'Authorization: token ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data '{
            "body": "Já está disponível no Guia Rails :tada: :rocket:"
          }' > /dev/null
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN   }}
      - name: Add label on merged pull request
          curl --silent --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels \
          --header 'Accept: application/vnd.github.squirrel-girl-preview' \
          --header 'Authorization: token ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data '{
            "labels": [":rocket:"]
          }' > /dev/null
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN   }}
